//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platform
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Platform()
        {
            this.VideoGame = new HashSet<VideoGame>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> SoldUnits { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
        public string Author { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoGame> VideoGame { get; set; }
    }
}
