//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIvgd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videojuego
    {
        public string Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public Nullable<int> VentasGenerados { get; set; }
        public Nullable<int> NumeroPlataformasDisponibles { get; set; }
        public string UsuarioID { get; set; }
        public string DistribuidoraID { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual Distribuidora Distribuidora { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
