//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrudAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public string Id { get; set; }
        public Nullable<bool> Played { get; set; }
        public Nullable<int> Mark { get; set; }
        public string Description { get; set; }
        public string UserID { get; set; }
        public string VideogameID { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Videojuego Videojuego { get; set; }
    }
}
