//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrudAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks
    {
        public int BranchOfficesID { get; set; }
        public int BicyclesID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Bicycles Bicycles { get; set; }
        public virtual BranchOffices BranchOffices { get; set; }
    }
}
